//1
console.log(document.getElementById("b_context"))
//2
console.log(document.getElementsByName("onload"))
//3
console.log(document.body.children[1])
//4
console.log(document.getElementsByTagName("h2").length)
//5
console.log(document.body.children[1].children[0].children[1].children[0].getAttribute("value"))
